"""changed temp senstive status to bool from str

Revision ID: 0786e0cf2fdc
Revises: 026bde5d969c
Create Date: 2022-07-22 22:31:27.338730

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0786e0cf2fdc'
down_revision = '026bde5d969c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
