"""removed fk on roles table

Revision ID: 15f1c5d89d1a
Revises: 66a971506b9a
Create Date: 2022-07-13 12:21:45.772787

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15f1c5d89d1a'
down_revision = '66a971506b9a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_roles_users_id_fkey', 'user_roles', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('user_roles_users_id_fkey', 'user_roles', 'users', ['users_id'], ['id'])
    # ### end Alembic commands ###
