"""removed temp sensitive

Revision ID: 2834b3b170c6
Revises: 0786e0cf2fdc
Create Date: 2022-07-22 22:36:02.514742

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2834b3b170c6'
down_revision = '0786e0cf2fdc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('supplies', 'temp_sensitive')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('supplies', sa.Column('temp_sensitive', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
