"""change to admin column int -> string

Revision ID: 3b10927e9acd
Revises: e46e9f98417f
Create Date: 2022-07-13 11:32:58.112273

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b10927e9acd'
down_revision = 'e46e9f98417f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
