"""re-added admin columns as strings

Revision ID: 66a971506b9a
Revises: c250c2b517df
Create Date: 2022-07-13 12:07:46.757893

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66a971506b9a'
down_revision = 'c250c2b517df'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('site_permissions', sa.Column('admin_created_by', sa.String(length=255), nullable=True))
    op.add_column('user_roles', sa.Column('admin_created_by', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_roles', 'admin_created_by')
    op.drop_column('site_permissions', 'admin_created_by')
    # ### end Alembic commands ###
