"""fk

Revision ID: 6c676a0b08cc
Revises: 904d0ee6711e
Create Date: 2022-06-12 23:07:31.381287

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c676a0b08cc'
down_revision = '904d0ee6711e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
