"""autogenerate base

Revision ID: 904d0ee6711e
Revises: e260d3b274d4
Create Date: 2022-06-12 23:05:52.749262

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '904d0ee6711e'
down_revision = 'e260d3b274d4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=255), nullable=False),
    sa.Column('last_name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_login', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('supplies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_name', sa.String(length=255), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('date_ordered', sa.Date(), nullable=False),
    sa.Column('order_status', sa.String(length=20), nullable=True),
    sa.Column('temp_sensitive', sa.String(length=20), nullable=True),
    sa.Column('recieved_by', sa.String(length=255), nullable=True),
    sa.Column('users_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['users_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('supplies')
    op.drop_table('users')
    # ### end Alembic commands ###
