"""readded temp sensitive v2

Revision ID: 906477e65b48
Revises: d327f154c233
Create Date: 2022-07-22 22:37:11.904714

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '906477e65b48'
down_revision = 'd327f154c233'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('supplies', sa.Column('temp_sensitive', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('supplies', 'temp_sensitive')
    # ### end Alembic commands ###
