"""added user roles and site permissions tables

Revision ID: 961e571a2fe4
Revises: 6c676a0b08cc
Create Date: 2022-07-13 10:36:11.902525

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '961e571a2fe4'
down_revision = '6c676a0b08cc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('site_permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('page_name', sa.String(length=255), nullable=False),
    sa.Column('role_required', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('users_id', sa.Integer(), nullable=True),
    sa.Column('role', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['users_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_roles')
    op.drop_table('site_permissions')
    # ### end Alembic commands ###
