"""added fk restraint to all tables with users_id

Revision ID: 9a5122f76b97
Revises: fc29a2187f53
Create Date: 2022-07-15 19:12:37.948767

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a5122f76b97'
down_revision = 'fc29a2187f53'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('email_verification', sa.Column('temp_jwt', sa.String(length=255), nullable=True))
    op.create_foreign_key(None, 'token_list', 'users', ['users_id'], ['id'])
    op.create_foreign_key(None, 'user_roles', 'users', ['users_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_roles', type_='foreignkey')
    op.drop_constraint(None, 'token_list', type_='foreignkey')
    op.drop_column('email_verification', 'temp_jwt')
    # ### end Alembic commands ###
