"""added fk and nullable constraints to email_verify table

Revision ID: a3e57a367968
Revises: 9a5122f76b97
Create Date: 2022-07-15 22:09:21.302237

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3e57a367968'
down_revision = '9a5122f76b97'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('email_verification', sa.Column('users_email', sa.String(length=100), nullable=False))
    op.alter_column('email_verification', 'temp_jwt',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('email_verification', 'users_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_foreign_key(None, 'email_verification', 'users', ['users_email'], ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'email_verification', type_='foreignkey')
    op.alter_column('email_verification', 'users_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('email_verification', 'temp_jwt',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.drop_column('email_verification', 'users_email')
    # ### end Alembic commands ###
