"""removing admin columns

Revision ID: c250c2b517df
Revises: 3b10927e9acd
Create Date: 2022-07-13 12:06:44.231539

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c250c2b517df'
down_revision = '3b10927e9acd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('site_permissions', 'admin_created_by')
    op.drop_column('user_roles', 'admin_created_by')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_roles', sa.Column('admin_created_by', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('site_permissions', sa.Column('admin_created_by', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
