"""readded temp sensitive

Revision ID: d327f154c233
Revises: 2834b3b170c6
Create Date: 2022-07-22 22:36:34.283692

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd327f154c233'
down_revision = '2834b3b170c6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
