"""added admin column to roles/permissions table

Revision ID: e46e9f98417f
Revises: 961e571a2fe4
Create Date: 2022-07-13 11:31:20.705468

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e46e9f98417f'
down_revision = '961e571a2fe4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('site_permissions', sa.Column('admin_created_by', sa.Integer(), nullable=True))
    op.add_column('site_permissions', sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('user_roles', sa.Column('admin_created_by', sa.Integer(), nullable=True))
    op.add_column('user_roles', sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_roles', 'created_at')
    op.drop_column('user_roles', 'admin_created_by')
    op.drop_column('site_permissions', 'created_at')
    op.drop_column('site_permissions', 'admin_created_by')
    # ### end Alembic commands ###
