name: CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
jobs:
  test:
    runs-on: ubuntu-latest
    steps:

      - name: pull code from repository
        uses: actions/checkout@v3

      - name: install python - 3.10.5
        uses: actions/setup-python@v4
        with:
            python-version: '3.10.5' 

      - name: update pip
        run: python -m pip install --upgrade pip

      - name: install dependacies
        run: pip install -r requirements.txt

      - name: run unit and integration tests
        run: pytest


