name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Pull code from git repository
      - uses: actions/checkout@v3
      - name: Print Hello to the Terminal
        run: echo "Hello Daniel"



